### ISSUE TITLE
[Docker] Volumes within db causes issue's on Windows

### ISSUE THREAD

**Issue by thebspin** [CodingGarden/inventory-app#1]
So on line 7 from the `docker-compose` file it says: `- ./docker-data/db-data:/var/lib/postgresql/data`
This works fine on my Mac but does not on Windows.
It complains about chmod (probabaly because docker is a different user?)
It is not something new perse (see https://github.com/docker-library/postgres/issues/435) and there are many other issue's on git about it. 

Being new myself to Docker i tried some stuff but i could not figure it out.
I hope you could tell me how to achieve the same on Windows so i could follow on my Desktop (and not laptop)

**Comment by w3cj** [comment]
Maybe something from this thread can help? https://github.com/docker/compose/issues/4303

**Comment by thebspin** [comment]
> Maybe something from this thread can help? [docker/compose#4303](https://github.com/docker/compose/issues/4303)

I've read multile issue's including that one.
But when using that doesn't it break when using a different system?
Correct me if i'm wrong but isn't the idea of having a docker-compose file that it's also system independent?

**Comment by jessikuh** [comment]
I'm not sure if you already solved the issue, but I am able to get docker-compose to execute correctly on Windows 10 by removing the '.' from the volume. See below.

```
    volumes:
      - /docker-data/db-data:/var/lib/postgresql/data
```

I read elsewhere that some people had to manually create the volume on Windows 10, as well, but this did the trick for me.

**Comment by thebspin** [comment]
@jessikuh 

Hmm i'm sure i would have tried it but yes indeed.. it spins up without any issues!
Would you also happen to know where exactly the docker-data is being saved on windows now?

**Comment by jessikuh** [comment]
With my little knowledge, I _think_ they're stored in the VM. It does look like you can copy volumes between your system and the container as [documented here](https://docs.docker.com/engine/reference/commandline/cp/). I hope that helps. :/

**Comment by thebspin** [comment]
Yeah that's what i was afraid off.. the idea of the volumes in CJ's example is that it's stored external i believe, so you don't lose the data. After i add some data, turn off the container and spin it up again i lost all my data now :(

**Comment by jessikuh** [comment]
I haven't experienced any data loss after stopping my container, only after shutting Docker off and on. If you seed your data with knex, you won't lose it since it'll be stored in the seed file.  Otherwise, you could install Postgres locally. :)

**Comment by Sageza-84** [comment]
` services:

  db:
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker-data/db-data:/etc/postgresql/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    
  adminer:
    depends_on: 
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres:`

works for me on win10 pro

**Comment by thebspin** [comment]
> works for me on win10 pro

Like this?

```
version: "3.1"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker-data/db-data:/etc/postgresql/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8090:8080
volumes:
  postgres:
```
