### ISSUE TITLE
Docker compose up not reading from .env file

### ISSUE THREAD

**Issue by abdelillah-bentegar** [CodingGarden/inventory-app#3]
So I'm following along what CJ did in the stream ,
i set up the docker-compose and .env as shown , but when running docker-compose up it says this 
The POSTGRES_PASSWORD variable is not set. Defaulting to a blank string.
The POSTGRES_USER variable is not set. Defaulting to a blank string.
The POSTGRES_DB variable is not set. Defaulting to a blank string.

**Comment by w3cj** [comment]
Make sure the `.env` was created _before_ running `docker-compose up`
 
If not, try deleting the `docker-data` folder, make sure the `.env` exists, and then try to start it up.

**Comment by pranxy** [comment]
If the .env file is not on the same folder, you can do something as I did.

```
environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
env_file:
      - ./api-node/.env
```
